const { GoogleGenAI } = require("@google/genai");
const { z } = require("zod");
const puppeteer = require("puppeteer");

const ai = new GoogleGenAI({
  apiKey: process.env.GOOGLE_GENAI_API_KEY,
});

const interviewReportSchema = z.object({
  matchScore: z.number(),

  technicalQuestions: z.array(
    z.object({
      question: z.string(),
      intention: z.string(),
      answer: z.string(),
    })
  ),

  behavioralQuestions: z.array(
    z.object({
      question: z.string(),
      intention: z.string(),
      answer: z.string(),
    })
  ),

  skillGaps: z.array(
    z.object({
      skill: z.string(),
      severity: z.enum(["low", "medium", "high"]),
    })
  ),

  preparationPlan: z.array(
    z.object({
      day: z.number(),
      focus: z.string(),
      tasks: z.array(z.string()),
    })
  ),

  title: z.string().describe("The title of the job for which the interview report is generated")
});

async function generateInterviewReport({
  resume,
  selfDescription,
  jobDescription,
}) {
  const prompt = `
You are an AI interview coach.

Analyze the candidate profile and generate an interview preparation report.

Resume:
${resume}

Self Description:
${selfDescription}

Job Description:
${jobDescription}

Return ONLY valid JSON in this format:

{
  "matchScore": number,
  "technicalQuestions": [
    {
      "question": "string",
      "intention": "string",
      "answer": "string"
    }
  ],
  "behavioralQuestions": [
    {
      "question": "string",
      "intention": "string",
      "answer": "string"
    }
  ],
  "skillGaps": [
    {
      "skill": "string",
      "severity": "low | medium | high"
    }
  ],
  "preparationPlan": [
    {
      "day": number,
      "focus": "string",
      "tasks": ["string"]
    }
  ]
    "title":"string
}

Return JSON only. No explanation.
`;



  const response = await ai.models.generateContent({
    model: "gemini-2.5-flash",
    contents: prompt,
    config: {
      responseMimeType: "application/json",

    },
  });


  const json = JSON.parse(response.text);
  const validated = interviewReportSchema.parse(json);
  return validated;

}

async function generatePdfFromHtml(htmlcontent) {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.setContent(htmlcontent, { waitUntil: "networkidle0" })
  const pdfBuffer = await page.pdf({
    format: "A4",
    margin: {
      top: "20mm",
      bottom: "20mm",
      left: "15mm",
      right: "15mm"
    }
  });

  await browser.close();
  return pdfBuffer
}

async function generateResumePdf({ resume, selfDescription, jobDescription }) {
  const resumepdfSchema = z.object({
    html: z.string().describe("The HTML content of resume which can be converted to PDF using any library like puppeteer")
  })

  const prompt = `Generate a resume for a candidate with the following details :
  Resume:${resume}
  Self Description :${selfDescription}
  JOb Description:${jobDescription}
  the response should be JSON object with a single field "html" which contains the HTML content of resume which can be converted to PDF using any library like puppeteer.
 the resume should be tailored to the job description and should highlight the skills and experiences mentioned in self description and resume that are relevant to the job description. The resume should be well formatted and should follow a professional structure. Return ONLY valid JSON in this format:

{
  "html": "string"
}
  the content of resume not sound like it is generated by AI. It should be natural and should have a human touch. Return JSON only. No explanation.
  you can highlight the content using some colors and different style but the overall design should be simple and professional.
  the content should be ATS friendly ,i.e it should be easily parsable by ATS systems without loosing important information.
  the resume should not be lengthy ,it should ideally be 1-2 pages long when converted to PDF.Focus on quality rather than quantity and make sure to include all the relevant information
  than can increase the candidate's chances of getting an interview call for the given job description.`

  const response = await ai.models.generateContent({
    model: "gemini-3-flash-preview",
    contents: prompt,
    config: {
      responseMimeType: "application/json",
    }
  })
  const json = JSON.parse(response.text);
  const validated = resumepdfSchema.parse(json);

  const pdfBuffer = await generatePdfFromHtml(validated.html)
  return pdfBuffer;

}

module.exports = { generateInterviewReport, generateResumePdf };